steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t',  'gcr.io/deft-duality-311814/github.com/fadox/kodic:$COMMIT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push',  'gcr.io/deft-duality-311814/github.com/fadox/kodic:$COMMIT_SHA', '.']
